system:
  os: mac

mqtt:
  broker: localhost
  port: 1883
  client_id: myk46
  timeout: 20
  max_retries: 3
  topic: "test/topic"
  retain: false
  qos: 1

camera:
  device_id: "Logitech Web Camera"
  device_path: 1
  timeout: 5

image:
  dimensions: [600,600]
